/*
**	Map WeaponSetType to ModelConditionFlagType. Include after DEFINE_WEAPONCONDITIONMAP.
*/

#ifndef __WEAPON_SET_CONDITION_MAP_H_
#define __WEAPON_SET_CONDITION_MAP_H_

#include "GameLogic/WeaponSetType.h"
#include "Common/ModelState.h"

#ifdef DEFINE_WEAPONCONDITIONMAP
static const ModelConditionFlagType TheWeaponSetTypeToModelConditionTypeMap[WEAPONSET_COUNT] =
{
	MODELCONDITION_WEAPONSET_VETERAN,
	MODELCONDITION_WEAPONSET_ELITE,
	MODELCONDITION_WEAPONSET_HERO,
	MODELCONDITION_WEAPONSET_PLAYER_UPGRADE,
	MODELCONDITION_WEAPONSET_CRATEUPGRADE_ONE,
	MODELCONDITION_WEAPONSET_CRATEUPGRADE_TWO
};
#endif

#endif
