#ifndef RENEGADE_WINERROR_H
#define RENEGADE_WINERROR_H

#include <windows.h>

#ifndef SEVERITY_SUCCESS
#define SEVERITY_SUCCESS 0
#endif
#ifndef SEVERITY_ERROR
#define SEVERITY_ERROR 1
#endif
#ifndef FACILITY_ITF
#define FACILITY_ITF 4
#endif
#ifndef FACILITY_WIN32
#define FACILITY_WIN32 7
#endif

#ifndef ERROR_ALREADY_EXISTS
#define ERROR_ALREADY_EXISTS 183L
#endif
#ifndef ERROR_FILE_EXISTS
#define ERROR_FILE_EXISTS 80L
#endif
#ifndef ERROR_PATH_NOT_FOUND
#define ERROR_PATH_NOT_FOUND 3L
#endif
#ifndef ERROR_INVALID_PARAMETER
#define ERROR_INVALID_PARAMETER 87L
#endif
#ifndef ERROR_WRITE_FAULT
#define ERROR_WRITE_FAULT 29L
#endif
#ifndef ERROR_INSUFFICIENT_BUFFER
#define ERROR_INSUFFICIENT_BUFFER 122L
#endif
#ifndef ERROR_INVALID_HANDLE
#define ERROR_INVALID_HANDLE 6L
#endif
#ifndef ERROR_MOD_NOT_FOUND
#define ERROR_MOD_NOT_FOUND 126L
#endif
#ifndef ERROR_PROC_NOT_FOUND
#define ERROR_PROC_NOT_FOUND 127L
#endif
#ifndef ERROR_FILE_NOT_FOUND
#define ERROR_FILE_NOT_FOUND 2L
#endif
#ifndef ERROR_BUSY
#define ERROR_BUSY 170L
#endif
#ifndef ERROR_ALREADY_INITIALIZED
#define ERROR_ALREADY_INITIALIZED 1247L
#endif
#ifndef ERROR_BAD_DRIVER_LEVEL
#define ERROR_BAD_DRIVER_LEVEL 1191L
#endif
#ifndef ERROR_RMODE_APP
#define ERROR_RMODE_APP 720L
#endif
#ifndef ERROR_READ_FAULT
#define ERROR_READ_FAULT 30L
#endif
#ifndef ERROR_INVALID_ACCESS
#define ERROR_INVALID_ACCESS 12L
#endif
#ifndef ERROR_NOT_READY
#define ERROR_NOT_READY 21L
#endif
#ifndef REGDB_E_CLASSNOTREG
#define REGDB_E_CLASSNOTREG ((HRESULT)0x80040154L)
#endif
#ifndef CLASS_E_NOAGGREGATION
#define CLASS_E_NOAGGREGATION ((HRESULT)0x80040110L)
#endif
#ifndef E_ACCESSDENIED
#define E_ACCESSDENIED ((HRESULT)0x80070005L)
#endif
#ifndef DRIVE_FIXED
#define DRIVE_FIXED 3
#endif

#endif
