// Linux bring-up placeholder (normally generated by buildVersionUpdate).
#define VERSION_STRING "1.8.0"
#define VERSION_MAJOR 1
#define VERSION_MINOR 8			///< This effects the replay version number.
#define VERSION_BUILDNUM 0
