/*
** INI name table for RadiusCursorType. Include after DEFINE_RADIUSCURSOR_NAMES.
*/
#ifdef DEFINE_RADIUSCURSOR_NAMES
static const char *TheRadiusCursorNames[] =
{
	"NONE",
	"ATTACK_DAMAGE_AREA",
	"ATTACK_SCATTER_AREA",
	"ATTACK_CONTINUE_AREA",
	"GUARD_AREA",
	"EMERGENCY_REPAIR",
	"FRIENDLY_SPECIALPOWER",
	"OFFENSIVE_SPECIALPOWER",
	"SUPERWEAPON_SCATTER_AREA",

	"PARTICLECANNON",
	"A10STRIKE",
	"CARPETBOMB",
	"DAISYCUTTER",
	"PARADROP",
	"SPYSATELLITE",

	"NUCLEARMISSILE",
	"EMPPULSE",
	"ARTILLERYBARRAGE",
	"NAPALMSTRIKE",
	"CLUSTERMINES",

	"SCUDSTORM",
	"ANTHRAXBOMB",
	"AMBUSH",
	"RADAR",
	"SPYDRONE",

	NULL
};
#endif
